// Date: 6/29/2013 3:16:43 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package renkin42.stuffWorthThrowing.client;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPlane extends ModelBase
{
  //fields
    ModelRenderer nose;
    ModelRenderer body;
    ModelRenderer frontWing;
    ModelRenderer backWing;
  
  public ModelPlane()
  {
    textureWidth = 32;
    textureHeight = 32;
    
      nose = new ModelRenderer(this, 0, 12);
      nose.addBox(-0.5F, -2F, 3F, 1, 2, 2);
      nose.setRotationPoint(0F, 24F, 0F);
      nose.setTextureSize(32, 32);
      nose.mirror = true;
      setRotation(nose, 0F, 0F, 0F);
      body = new ModelRenderer(this, 0, 0);
      body.addBox(-0.5F, -4F, -5F, 1, 4, 8);
      body.setRotationPoint(0F, 24F, 0F);
      body.setTextureSize(32, 32);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      frontWing = new ModelRenderer(this, 6, 12);
      frontWing.addBox(-1.5F, -5F, -1F, 3, 1, 2);
      frontWing.setRotationPoint(0F, 24F, 0F);
      frontWing.setTextureSize(32, 32);
      frontWing.mirror = true;
      setRotation(frontWing, 0F, 0F, 0F);
      backWing = new ModelRenderer(this, 0, 16);
      backWing.addBox(-3F, -5F, -5F, 6, 1, 4);
      backWing.setRotationPoint(0F, 24F, 0F);
      backWing.setTextureSize(32, 32);
      backWing.mirror = true;
      setRotation(backWing, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    nose.render(f5);
    body.render(f5);
    frontWing.render(f5);
    backWing.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    nose.rotateAngleY = f3 / (180F / (float)Math.PI);
    body.rotateAngleY = f3 / (180F / (float)Math.PI);
    frontWing.rotateAngleY = f3 / (180F / (float)Math.PI);
    backWing.rotateAngleY = f3 / (180F / (float)Math.PI);
  }

}
